export const SUPABASE_URL = 'https://wlvmisbloklmcnqjqcwf.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indsdm1pc2Jsb2tsbWNucWpxY3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE5ODMwMzEsImV4cCI6MjA5NzU1OTAzMX0.G_UMy9mAcfAbCqpi-NzmQIpNQ6FZH92jzFoojenzFvg';
